# Generated by Django 4.0.6 on 2022-07-28 09:55

from django.db import migrations, models
import loginDemo.aws.backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=loginDemo.aws.backend.Media_Storage1(), upload_to='')),
            ],
        ),
    ]
