# Generated by Django 4.0.6 on 2022-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_kind',
            field=models.CharField(default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_kind',
            field=models.CharField(choices=[('1', 'Premium'), ('2', 'Tier-1'), ('3', 'Tier-2'), ('4', 'Other')], max_length=1),
        ),
    ]
